apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: django-aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: django-backend-db-secret
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: django-notes-eks-prod-db-credentials
        property: password
